branch-defaults:
  default:
    environment: prod-nocodb
environment-defaults:
  prod-nocodb:
    branch: null
    repository: null
global:
  application_name: nocodb.goomer.com.br
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
